//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfWebView.Strings {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfWebView.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wts.ItemName.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wts.ItemName.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageBackButtonTooltip
        /// </summary>
        public static string WebViewPageBackButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageBackButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageForwardButtonTooltip
        /// </summary>
        public static string WebViewPageForwardButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageForwardButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageLoadingText
        /// </summary>
        public static string WebViewPageLoadingText {
            get {
                return ResourceManager.GetString("WebViewPageLoadingText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageFaildedMessage
        /// </summary>
        public static string WebViewPageFaildedMessage {
            get {
                return ResourceManager.GetString("WebViewPageFaildedMessage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageRefreshButtonTooltip
        /// </summary>
        public static string WebViewPageRefreshButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageRefreshButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageOpenInBrowserButtonTooltip
        /// </summary>
        public static string WebViewPageOpenInBrowserButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageOpenInBrowserButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebView.
        /// </summary>
        public static string ShellWebViewPage {
            get {
                return ResourceManager.GetString("ShellWebViewPage", resourceCulture);
            }
        }
    }
}
